---
title: Pictogrammen van Python Turtle wijzigen
hero_image: images/banner.png
description: Hoe je de afbeelding van de Python Turtle verwisselt
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - 
    title: Python Turtle afbeeldingen
