title: Using Python turtle images
hero_image: images/banner.png
description: Using Python turtle images
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: Turtle images
