---
title: Python Turtle icons बदलने
hero_image: images/banner.png
description: Python Turtle प्रतिमांची अदलाबदल कशी करावी
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: Python Turtle प्रतिमा
