---
title: 更改 Python Turtle 图标
hero_image: images/banner.png
description: 如何更改 Python Turtle的图标
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "图形"
technologies: "python, 海龟"
steps:
  - 
    title: Python Turtle 图标
