---
title: Cambiar los iconos de la tortuga (turtle) de Python
hero_image: images/banner.png
description: Cómo cambiar la imagen de la tortuga (turtle) de Python
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: Imágenes de la tortuga (turtle) de Python
