---
title: Python Turtle Icons ändern
hero_image: images/banner.png
description: Wie man das turtle-Bild in Python ersetzt
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - 
    title: Python Turtle Bilder
