---
title: Schimbarea pictogramelor Turtle în Python
hero_image: images/banner.png
description: Cum să schimbi pictograma Turtle în Python
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - 
    title: Imagini Turtle în Python
