---
title: Alterando os ícones da tartaruga do Python
hero_image: imagens/banner.png
description: Como trocar a imagem da tartaruga no Python
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, tartaruga"
steps:
  - 
    title: Imagens de tartaruga do Python
