---
title: Cambiando los iconos de Python Tortuga (Turtle)
hero_image: imagenes/banner.png
description: Cómo intercambiar la imagen de la tortuga (turtle) de Python
original_url:
theme: cc-prototipo
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - 
    title: Imágenes de Python Tortuga
