---
title: تغيير أيقونات Python Turtle
hero_image: images/banner.png
description: كيفية تبديل صورة "Python Turtle"
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - 
    title: صور Python Turtle
