---
title: Changing Python Turtle icons
hero_image: images/banner.png
description: How to swap the Python Turtle image
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "그래픽"
technologies: "python, turtle"
steps:
  - 
    title: Python Turtle images
