---
title: Zmiana ikon żółwia Pythona
hero_image: images/banner.png
description: Jak zamienić obraz żółwia Pythona
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "grafika"
technologies: "python, żółw"
steps:
  - 
    title: Obrazki żółwia Pythona
