---
title: Modifier les icônes de Python Turtle
hero_image: images/banner.png
description: Comment échanger l'image de Python Turtle
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - 
    title: Images de Python Turtle
