---
title: Python Turtle simgelerini değiştirme
hero_image: images/banner.png
description: Python Turtle resmi nasıl değiştirilir
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: Python Turtle resimleri
